Added error404 page + improved homepage css (WIP)
aston-cs2tp-evotech/evotech pull request #38
Opened 2023-12-05 22:25 UTC by realhanzalah

if any collisions for homepage then use this version as its the improved one, still work in progress. should've done the error page as a separate branch to the homepage improvements but they're under the same branch now. homepage improvements ill put more under a new branch when I next work on it.

2023-12-05 22:27 UTC, Aaron3455454 approved these changes

2023-12-05 22:33 UTC, realhanzalah commented
I've resolved conflicts now

2023-12-05 22:41 UTC, YourKalamity requested changes

2023-12-05 22:41 UTC, YourKalamity commented on view/error404.php
> +    <link rel="stylesheet" href="css/error404.css">
Please reference the full link for the CSS to ensure it’s compatible with the routing `/view/css/error404.css`

2023-12-05 22:41 UTC, YourKalamity commented on view/error404.php
> +        <p>Return to <a href="home.php">home</a>.</p>
Change the href here to just home without any extensions

2023-12-05 22:41 UTC, YourKalamity commented on view/home.php
>      <link rel="stylesheet" type="text/css" href="view/css/home.css">
Update the CSS linking here as well just like I stated in a previous comment

2023-12-05 22:41 UTC, YourKalamity commented on view/home.php
> +            <img src="images/Picture1.png" style="width: 50px; height: 50px;" alt="Evotech Logo">
Another linking that needs to have view/ before images/ (view/images/…)

2023-12-05 22:41 UTC, YourKalamity commented on view/home.php
> +                            <a class="nav-link active" aria-current="page" href="home.php">Home</a>
This should just be home

2023-12-05 22:41 UTC, YourKalamity commented on view/home.php
> +                            <a class="nav-link" href="aboutus.php">About</a>
This should just be aboutus

2023-12-05 22:41 UTC, YourKalamity commented on view/home.php
> +               <img class="img-fluid w-10" src="images/Picture1.png"alt="Evotech">
This linking requires view before images

2023-12-05 22:42 UTC, YourKalamity commented on view/home.php
> +                            <a class="nav-link" href="aboutus.php">About</a>
Without the php extension

2023-12-06 11:35 UTC, YourKalamity approved these changes

2023-12-06 11:35 UTC, merged