footer
aston-cs2tp-evotech/evotech pull request #75
Opened 2023-12-09 21:55 UTC by gurjotsd

ive added the footer and done a simple css

2023-12-09 22:45 UTC, gurjotsd commented
made some chnages to css and html to make I t look better

2023-12-09 23:24 UTC, gurjotsd commented
made css better

2023-12-10 11:40 UTC, YourKalamity approved these changes

2023-12-10 11:44 UTC, YourKalamity requested changes
I believe what @Aaron3455454 asked for was a `footer.php` similar to `nav.php`

2023-12-10 12:00 UTC, merged